artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/0/e54755842f854c5f957a6ff8c02289f5/artifacts
end_time: 1772284504735
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: e54755842f854c5f957a6ff8c02289f5
run_name: Default
run_uuid: e54755842f854c5f957a6ff8c02289f5
source_name: ''
source_type: 4
source_version: ''
start_time: 1772284504727
status: 3
tags: []
user_id: mle-user
